### ISSUE TITLE
libraries not found and code reference

### ISSUE THREAD

**Issue by joaoantoniocardoso** [HubertD/f0x2-can-breakout#1]
Hi, I just opened the schematic and got this error:

> The following libraries were not found:
> - con_debug
> - nxp_tja
> - stm32_xor

Where can I get those libs?

Also, i'm studying to design a very similar board, do you have some implemented code using its CAN controller? 

Thanks

**Comment by HubertD** [comment]
unfortunately, I don't have these library around any more. all the parts there should, however, be part of the kicad standard library now. suppose you want to use these, if you want to make a new schematic.

however, the library cache is in the repository, so I expect, apart from the error messages, the kicad schematic is perfectly working for you? if you really want to, you can extract the parts from there.

one firmware that uses basically the same hardware is in the candleLight-fw repo:
https://github.com/HubertD/candleLight_fw
